### ISSUE TITLE
Fix include of Arduino.h to header files

### ISSUE THREAD

**Issue by MartinRusk** [MartinRusk/XPLDevices#1]

**Comment by GioCC** [comment]
@MartinRusk You could remove the include from the .cpp files, it's recalled through the .h files anyway.

**Comment by MartinRusk** [comment]
I know. But then the ".h" needs to be above the <XPLDirect.h> and that looked ugly. 
But I don't insist on it.

**Comment by GioCC** [comment]
That's ok, I just thought maybe it slipped you.
