### ISSUE TITLE
Missing time delay after writing MUX selector lines

### ISSUE THREAD

**Issue by MartinRusk** [MartinRusk/XPLDevices#13]

**Comment by MartinRusk** [comment]
There is no delay after writing the 4 selector lines so the mux does not settle. Was well known from my original RSG implementation and forgot about it. 5µs will do.

**Comment by GioCC** [comment]
That's ironic after having tried to make it as fast as possible! 😂
Didn't expect it to be so slow... maybe due to some stray capacitance on the input lines rather than to the switching speed of the component itself?

**Comment by MartinRusk** [comment]
It was more a bug of using getBit() instead of bitRead() 🙈🙄🤣
I left one µs in for safety reasons. Did a direct checkin to master.
