### ISSUE TITLE
use direct port access for MUX selector lines

### ISSUE THREAD

**Issue by MartinRusk** [MartinRusk/XPLDevices#3]
Bypass the digitalWrite. Further optimization is possible by only once saving SREG and setting cli().

**Comment by GioCC** [comment]
Do you prefer this done through a dedicated "directOut" function inside DigitalIn (as in my example), or adding the directIO.* files (if you think they could be used elsewhere anytime soon)?

**Comment by MartinRusk** [comment]
I would do it inside, even without a method to save the call overhead. Just in the handle().

**Comment by GioCC** [comment]
To save the call I could just inline it. It would remain in the .cpp anyway, it's a regular function.

**Comment by MartinRusk** [comment]
I would even group all 4 writes under one cli() to save more time. We need it only for this purpose here.

**Comment by GioCC** [comment]
True. In this case it makes sense to incorporate it fully in the method.

**Comment by MartinRusk** [comment]
I have replaced in parallel the digitalRead. Works so far. I would be curious about a comparing speed test.

**Comment by GioCC** [comment]
Me too. Probably not groundbreaking in the scope of the whole program, but still inexpensive and not hurting.

**Comment by MartinRusk** [comment]
Speed comparison for 6 MUX (on G1000): 1394 vs 978 cycles per second for DigitalIn.handle() only. 

With all devices and xloop: 480Hz -> 620Hz. So somehow significant.
